//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRepeatRequester {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebRepeatRequester_strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebRepeatRequester_strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebRepeatRequester.WebRepeatRequester.strings", typeof(WebRepeatRequester_strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Invalid SSL.
        /// </summary>
        internal static string AcceptInvalidSSL {
            get {
                return ResourceManager.GetString("AcceptInvalidSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Match Settings.
        /// </summary>
        internal static string EditMatchSettings {
            get {
                return ResourceManager.GetString("EditMatchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Request Headers.
        /// </summary>
        internal static string EditRequestHeaders {
            get {
                return ResourceManager.GetString("EditRequestHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        internal static string Once {
            get {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST Data (leave blank for GET request).
        /// </summary>
        internal static string POSTDataleaveblankforGETrequest {
            get {
                return ResourceManager.GetString("POSTDataleaveblankforGETrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrer.
        /// </summary>
        internal static string Referrer {
            get {
                return ResourceManager.GetString("Referrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting.
        /// </summary>
        internal static string Requesting {
            get {
                return ResourceManager.GetString("Requesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File As.
        /// </summary>
        internal static string SaveFileAs {
            get {
                return ResourceManager.GetString("SaveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        internal static string URI {
            get {
                return ResourceManager.GetString("URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent (for alternate, separate with &apos;#&apos;).
        /// </summary>
        internal static string UserAgentforalternateseparatewith {
            get {
                return ResourceManager.GetString("UserAgentforalternateseparatewith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Matches.
        /// </summary>
        internal static string ViewMatches {
            get {
                return ResourceManager.GetString("ViewMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Repeat Requester.
        /// </summary>
        internal static string WebRepeatRequesterr {
            get {
                return ResourceManager.GetString("WebRepeatRequesterr", resourceCulture);
            }
        }
    }
}
